### ISSUE TITLE
Foo

### ISSUE THREAD

**Issue by jeffebauer** [chrislloyd/brains#2]
Bar

**Comment by jeffebauer** [comment]
Extra bar

**Comment by toolmantim** [comment]
Foo

**Comment by toolmantim** [comment]
:sparkles:

**Comment by toolmantim** [comment]
Really disappointed that you've closed this issue. I thought open source was about openly accepting contributions and giving everyone their say.

I want my :dollar: back

**Comment by chrislloyd** [comment]
Sorry, just testing out Github's notifications.

Here is your :dollar: back.

**Comment by whatupdave** [comment]
I'm surprised nobody suggested Baz. I think Baz would solve this.

**Comment by toolmantim** [comment]
I'm pleased to see @whatupdave understands what Open Source really means. Glad to see this issue is still being considered.

For the moment I'm happy for you to keep my :dollar:

**Comment by chrislloyd** [comment]
Here's a preview of Brains 2:

![test](https://cloud.githubusercontent.com/assets/718/3581002/c16f88fe-0be2-11e4-8965-e44f84086d7e.gif)

**Comment by toolmantim** [comment]
there's not even a cat in that gif

**Comment by chrislloyd** [comment]
Cats were the first to go in the apocalypse. So much attitude, so little meat.

**Comment by toolmantim** [comment]
May they always be remembered in our gifs.

**Comment by toolmantim** [comment]
:skull:
